# 13.7, name:iPhone 8 is available on 2020 october
name: Swift

on:
  push:
     branches:
       - master
       - develop
  pull_request:
     branches: 
     - master
     - develop

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Run fastlane setup
      run: |
          cd Bank\ App/
      shell: bash
    - name: Compile and Upload
      uses: maierj/fastlane-action@v1.4.0
      with:
        lane: "buildAndTests"