# 13.7, name:iPhone 8 is available on 2020 october
name: Swift

on:
  push:
     branches:
       - master
       - develop
  pull_request:
     branches: 
     - master
     - develop

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: ty0x2333/cocoapods-action@master
      - name: Install Dependencies
        run: |
          cd Bank\ App/
          pod install --repo-update
        shell: bash
      - uses: actions/checkout@v2
      - name: Build/tests
        run: |
            cd Bank\ App/
            xcodebuild test -workspace Bank\ App.xcworkspace -scheme BankApp -destination 'platform=iOS Simulator,name=iPhone 8,OS=13.7'
