# 13.7, name:iPhone 8 is available on 2020 october
name: Swift

on:
  push:
     branches:
       - master
       - develop
  pull_request:
     branches: 
     - master
     - develop

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: ty0x2333/cocoapods-action@master
      - name: Run tests on fastlane
        run: |
          cd Bank\ App/
          fastlane buildAndTests
        shell: bash